cmake_minimum_required(VERSION 3.16)
project(shuangsheng_pinyin_bridge LANGUAGES CXX)
find_package(LibIMEPinyin 1.1.5 REQUIRED)
find_file(PINYIN_DICT sc.dict HINTS "${LIBIME_INSTALL_PKGDATADIR}" PATH_SUFFIXES libime REQUIRED)
add_executable(shuangsheng-pinyin-bridge main.cpp)
target_compile_features(shuangsheng-pinyin-bridge PRIVATE cxx_std_20)
target_compile_definitions(shuangsheng-pinyin-bridge PRIVATE PINYIN_DICT="${PINYIN_DICT}")
target_link_libraries(shuangsheng-pinyin-bridge PRIVATE LibIME::Pinyin)
install(TARGETS shuangsheng-pinyin-bridge RUNTIME DESTINATION bin)
