[Addon]
Name=Shuangsheng
Comment=Offline Chinese pinyin and Mandarin/Cantonese dictation
Category=InputMethod
Type=SharedLibrary
Library=shuangsheng
OnDemand=True
Configurable=False
Version=0.2.0

[Addon/Dependencies]
0=core
